---
title: "Final Project Quarto"
format: html
---

# Project Overview
Colorado ranks fourth in the United States for the total number of craft breweries, reflecting a strong local craft beer culture. This project examines how the distribution and what types of breweries intersect with neighborhood economic conditions, and how these factors influence award recognition. By considering both economic and social dimensions, we explore how craft breweries not only reflect but also shape access, opportunity, and community engagement across different regions.

Beer API: https://www.openbrewerydb.org/
Poverty API: https://www.census.gov/data/developers/data-sets/Poverty-Statistics.html 
Colorado Brewers Cup:https://coloradobeer.org/brewers-cup/ 
Great American Beer Fest: https://www.greatamericanbeerfestival.com/the-competition/winners/ 


### County poverty rate Colorado

```{python}

import requests
import pandas as pd

url = "https://api.census.gov/data/2021/acs/acs5"

params = {
    'get': 'NAME,B17001_002E,B17001_001E',
    'for': 'county:*', 
    'in': 'state:08'  #### REMEMBER TO CHANGE THIS IF YOU WANT TO CHANGE THE STATE!!!
}

response = requests.get(url, params=params)
data = response.json()


df = pd.DataFrame(data[1:], columns=data[0])


df['poverty_rate'] = (df['B17001_002E'].astype(int) / df['B17001_001E'].astype(int)) * 100

print(df)

```

### Poverty Rate by Zipcode

```{python}
import requests
import pandas as pd

url = "https://api.census.gov/data/2021/acs/acs5"

params = {
    'get': 'NAME,B17001_002E,B17001_001E',
    'for': 'zip code tabulation area:*'
}

response = requests.get(url, params=params)
data = response.json()


df = pd.DataFrame(data[1:], columns=data[0])


df['poverty_rate'] = (df['B17001_002E'].astype(int) / df['B17001_001E'].astype(int)) * 100


df['zip_state'] = df['zip code tabulation area'].str[:2]
co_df = df[df['zip_state'].isin(['80', '81'])]



```

-- Saved results to a CSV

# Brewery API Pull for Colorado

```{python}
import requests
import pandas as pd

BASE_URL = "https://api.openbrewerydb.org/v1/breweries"
all_breweries = []

try:
    page = 1
    while True:
        co = requests.get(BASE_URL, params={"by_state": "Colorado", "per_page": 200, "page": page}) ### Change state here!!!
        items = co.json()
        if not items:
            break
        all_breweries.extend(items)
        page += 1
except requests.RequestException:
    pass

columns = ["name", "brewery_type", "city", "state", "postal_code", "website_url"]

df = pd.DataFrame(all_breweries)[columns]

df['postal_code'] = df['postal_code'].astype(str).str[:5]
```

-- Saved results to a CSV

# Colorado Brewers Cup awards

```{python}
import requests
from bs4 import BeautifulSoup
import pandas as pd

def cbc():
    url = "https://coloradobeer.org/brewers-cup/"
    
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    }
    
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        
        soup = BeautifulSoup(response.content, 'html.parser')
        
        beer_data = []

        tables = soup.find_all('table')
        
        for table in tables:
            for row in table.find_all('tr'):
                cells = row.find_all('td')

                if len(cells) >= 6:
                    entry = {
                        'category': cells[0].get_text(strip=True),
                        'beer_name': cells[2].get_text(strip=True),  
                        'brewery': cells[3].get_text(strip=True),    
                        'city': cells[4].get_text(strip=True),       
                        'subcategory': cells[5].get_text(strip=True) 
                    }
                    beer_data.append(entry)
        
        return beer_data
        
    except Exception as e:
        return []

data = cbc()

df = pd.DataFrame(data)
#df.to_csv('colorado_beer_awards.csv', index=False)

```

--- Saved Results to a csv

# Get GABF results 

```{python}
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.greatamericanbeerfestival.com/2025-winners/"
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

data = []
for table in soup.find_all('table'):
    for row in table.find_all('tr'):
        cells = row.find_all('td')
        if len(cells) < 4:
            continue
            
        medal_text = cells[0].get_text().lower()
        if 'gold' in medal_text:
            medal = 'Gold'
        elif 'silver' in medal_text:
            medal = 'Silver'
        elif 'bronze' in medal_text:
            medal = 'Bronze'
        else:
            continue

        beer_name = cells[1].get_text(strip=True)
        brewery = cells[2].get_text(strip=True)
        city = cells[3].get_text(strip=True)
        
        state = ""
        category = ""
        for i, cell in enumerate(cells):
            if '_state' in str(cell.get('class', [])):
                state = cell.get_text(strip=True)
                if i + 1 < len(cells):
                    category = cells[i + 1].get_text(strip=True)
                break
        
        data.append({
            'medal': medal,
            'beer_name': beer_name,
            'brewery': brewery, 
            'city': city,
            'state': state,
            'category': category
        })

df = pd.DataFrame(data)

#df.to_csv("gabf_2025_winners_fixed.csv", index=False)
```

# Join GABF and Colorado Breweries API results

```{python}
import pandas as pd

winners = pd.read_csv("C:/Users/court/Downloads/Unstructered_final_project/Data_Dump/gabf_fixed.csv")
breweries = pd.read_csv("C:/Users/court/Downloads/Unstructered_final_project/Data_Dump/breweries_co_or_zip08.csv")


winners['brewery_clean'] = winners['brewery'].str.lower().str.strip().str.replace(' ', '').str.replace(r'[^\w\s]', '', regex=True)



winners['brewery_norm'] = winners['brewery'].str.replace(r'(?i)\b(?:company|co\.?)\b', 'Co', regex=True).str.split('-', n=1).str[0].str.strip()
breweries['name_norm'] = breweries['name'].str.replace(r'(?i)\b(?:company|co\.?)\b', 'Co', regex=True).str.split('-', n=1).str[0].str.strip()

winners['brewery_clean'] = winners['brewery_norm'].str.lower().str.strip().str.replace(r'[^\w\s]', '', regex=True).str.replace(' ', '')
breweries['name_clean'] = breweries['name_norm'].str.lower().str.strip().str.replace(r'[^\w\s]', '', regex=True).str.replace(' ', '')

winners.drop(columns=['brewery_norm'], inplace=True)
breweries.drop(columns=['name_norm'], inplace=True)

result = winners.merge(breweries, left_on='brewery_clean', right_on='name_clean', how='left')


result = result.drop(['brewery_clean', 'name_clean'], axis=1)

result
```


# Join Colorado Breweries and Colorado Brewers Cup Winners 


```{python}
import pandas as pd

colorado_awards = pd.read_csv("C:/Users/court/Downloads/Unstructered_final_project/Data_Dump/colorado_beer_awards.csv")

breweries = pd.read_csv("C:/Users/court/Downloads/Unstructered_final_project/Data_Dump/breweries_co_or_zip08.csv")

colorado_awards['brewery_clean'] = colorado_awards['brewery'].str.lower().str.strip().str.replace(r'[^\w\s]', '', regex=True).str.replace(' ', '')

breweries['name_clean'] = breweries['name'].str.lower().str.strip().str.replace(r'[^\w\s]', '', regex=True).str.replace(' ', '')

colorado_awards['brewery_norm'] = colorado_awards['brewery'].str.replace(r'(?i)\b(?:company|co\.?)\b', 'Co', regex=True).str.split('-', n=1).str[0].str.strip()

breweries['name_norm'] = breweries['name'].str.replace(r'(?i)\b(?:company|co\.?)\b', 'Co', regex=True).str.split('-', n=1).str[0].str.strip()

colorado_awards['brewery_clean'] = colorado_awards['brewery_norm'].str.lower().str.strip().str.replace(r'[^\w\s]', '', regex=True).str.replace(' ', '')

breweries['name_clean'] = breweries['name_norm'].str.lower().str.strip().str.replace(r'[^\w\s]', '', regex=True).str.replace(' ', '')

colorado_awards.drop(columns=['brewery_norm'], inplace=True)
breweries.drop(columns=['name_norm'], inplace=True)
colorado_result = colorado_awards.merge(breweries, left_on='brewery_clean', right_on='name_clean', how='left')

colorado_result = colorado_result.drop(['brewery_clean', 'name_clean'], axis=1)

colorado_result
```


# Join Colorado Breweries x GAMF x Colrado Cup

```{python}
import pandas as pd
import re

colorado_awards = pd.read_csv("C:/Users/court/Downloads/Unstructered_final_project/cbcxcoloradobrews.csv")
gabf_winners = pd.read_csv("C:/Users/court/Downloads/Unstructered_final_project/gabfxcoloradobrews.csv")
breweries = pd.read_csv("C:/Users/court/Downloads/Unstructered_final_project/Data_Dump/breweries_co_or_zip08.csv")

pattern = r'(?i)\b(?:company|co\.?)\b'

def clean_name(name):
    if pd.isna(name):
        return ''
    return re.sub(r'[^\w\s]', '', str(name).lower()).strip().replace(' ', '')

def clean_beer(beer_name):
    if pd.isna(beer_name):
        return ''
    return re.sub(r'[^\w\s]', '', str(beer_name).lower()).strip().replace(' ', '')

breweries['name_clean'] = breweries['name'].apply(clean_name)
colorado_awards['brewery_clean'] = colorado_awards['brewery'].apply(clean_name)
gabf_winners['brewery_clean'] = gabf_winners['brewery'].apply(clean_name)

colorado_awards['beer_norm'] = colorado_awards['beer_name'].apply(clean_beer)
gabf_winners['beer_norm'] = gabf_winners['beer_name'].apply(clean_beer)

colorado_awards['beer_id'] = colorado_awards['brewery_clean'] + '_' + colorado_awards['beer_norm']
gabf_winners['beer_id'] = gabf_winners['brewery_clean'] + '_' + gabf_winners['beer_norm']

colorado_clean = colorado_awards.copy()
colorado_clean['colorado_cup_medal'] = 'Colorado Cup Winner'
colorado_clean = colorado_clean.rename(columns={
    'category': 'colorado_cup_category', 
    'beer_name': 'colorado_cup_beer',
    'subcategory': 'colorado_cup_subcategory'
})

gabf_clean = gabf_winners.copy()
gabf_clean = gabf_clean.rename(columns={
    'medal': 'gabf_medal',
    'category': 'gabf_category',
    'beer_name': 'gabf_beer'
})

master_brewery_list = breweries.copy()

master_brewery_list = pd.merge(
    master_brewery_list,
    colorado_clean[['brewery_clean', 'beer_id', 'colorado_cup_medal', 'colorado_cup_category', 'colorado_cup_beer', 'colorado_cup_subcategory']],
    left_on='name_clean',
    right_on='brewery_clean',
    how='left'
)

gabf_temp = gabf_clean[['beer_id', 'gabf_medal', 'gabf_category', 'gabf_beer']].copy()

master_brewery_list = pd.merge(
    master_brewery_list,
    gabf_temp,
    on='beer_id',
    how='left'
)

master_brewery_list = master_brewery_list.drop(columns=['name_clean', 'brewery_clean', 'beer_id']).reset_index(drop=True)


master_brewery_list_final = master_brewery_list.drop_duplicates(subset=['name', 'colorado_cup_beer', 'gabf_beer'])

master_brewery_list_final
```

# Complete Join By Adding Poverty Data 

```{python}
import pandas as pd


master_breweries = pd.read_csv("C:/Users/court/Downloads/Unstructered_final_project/coloradobrewsxawards.csv")

poverty_data = pd.read_csv("C:/Users/court/Downloads/poverty.csv")

master_breweries['postal_code'] = master_breweries['postal_code'].astype(str)
poverty_data['zip'] = poverty_data['zip'].astype(str)

Final_Join = master_breweries.merge(
    poverty_data,
    left_on='postal_code',
    right_on='zip',
    how='left'
)

Final_Join = Final_Join.drop('zip', axis=1)

Final_Join 

```

# Quick Stats 

```{python}
#Drop duplicate brewery names for basic calcs
Final_Join_unique = Final_Join.drop_duplicates(subset=['name'])
```

```{python}
Final_Join_unique.describe()
```

```{python}
#State Average Poverty Rate
Avg_poverty = co_df['poverty_rate'].mean()
Avg_poverty
```

```{python}
# Average poverty rate for zipcodes with at least one craft brewery
zip_means = Final_Join.groupby('postal_code')['poverty_rate'].mean()
zip_means.mean()
```


```{python}
# Create Flag for award winners
Final_Join['medal_flag'] = (
    (Final_Join['colorado_cup_medal'].notnull())|
    (Final_Join['gabf_medal'].notnull())
).astype(int)

# Create Flag for Breweries over of Under State Avg Poverty

Final_Join['Above_Avg_poverty'] = (Final_Join['poverty_rate'] > Avg_poverty).astype(int)

Final_Join
```

```{python}
#Break down of brewery types
Final_Join_unique['brewery_type'].value_counts()
```

```{python}
# Brewery Type split on Pverty Flag
Final_Join_unique['Above_Avg_poverty'] = (Final_Join_unique['poverty_rate'] > Avg_poverty).astype(int)


Final_Join_unique.groupby(['Above_Avg_poverty', 'brewery_type']).size()
```

```{python}
# Breweries above or below poverty flag 
Final_Join_unique['Above_Avg_poverty'].value_counts()
```

# Next Steps

Early observations reveal a clear divide in access to craft beer. Experimental microbreweries, which often push the boundaries with innovative brewing techniques, are predominantly located in more affluent areas. In contrast brewpubs which frequently serve as community gathering spaces are more common in regions with higher poverty rates. This suggests that both economic factors and neighborhood demographics may influence the type of breweries present in an area. Now that we have a lead in the data, I turned to Tableau to examine the Draft Gap in depth. The visualizations above provide a clearer view of these patterns.

# Conclsuion 

The Draft Gap, examines how Colorado’s economic divide shapes one of its signature industries: craft beer. A comparison of ZIP codes above and below the state’s average poverty rate highlights distinct economic sectors. And when the focus narrows to ZIP codes with at least one brewery, disparities become even more visible, only 172/448 breweries operate in areas with a below-average poverty rate. 

Two themes emerge from this pattern: the dual engines of the industry and the inequity of recognition. Colorado’s brewery landscape is dominated by two types of producers, microbreweries and brewpubs, each serving a different role. Surprisingly, only 37% of microbreweries are located in higher-poverty regions, despite having lower start-up costs than brewpubs. Brewpubs, which combine brewing with a restaurant component, show a slightly stronger presence in these communities at 42%.
 
Brewpubs often function as local gathering spaces, reinforcing social cohesion in economically insecure areas, while microbreweries tend to specialize in experimental products that advance brewing techniques and draw industry attention. 

Recognition in the industry is driven largely by two key awards (1) the Colorado Brewers Cup and (2) the highly sought-after Great American Beer Festival medals. Because microbreweries cluster in more affluent ZIP codes, breweries in those areas receive a disproportionate share of awards. As a result, many brewpubs (despite producing high-quality beer) are held back by limited funding, reduced visibility, and fewer resources to compete for those recognitions. 

This imbalance matters in a state where the average brewery lifespan is estimated at 6.5 years and the national industry is contracting. Although earlier research suggested award outcomes did not strongly affect long-term survival, it also found brewpubs exited the market more frequently, hinting at deeper socio-economic dynamics. When these dynamics are viewed together (brewery type, neighborhood conditions, and award distribution) a pattern emerges in which breweries in less affluent areas struggle to gain recognition and market footholds. In an increasingly crowded industry, such recognition may be more critical than ever for survival and community impact. 

While Colorado represents only one case within a broader industry, the patterns here highlight how supporting access, visibility, and long-term stability for breweries across all communities can reinforce the strength of the craft beer sector and the connections people build around it.

